services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orga
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orga || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/orga
      APP_ENV: docker
      APP_DEBUG: "false"
      PYTHONPATH: /app/backend:/app
      ALEMBIC_CONFIG: /app/backend/alembic.ini
    working_dir: /app/backend
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 60
    command: ["/bin/bash","-lc","./docker/entrypoint.sh"]
    ports:
      - "8000:8000"
