services:
  db:
    image: postgres:15
    container_name: orga_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-orga}
      POSTGRES_USER: ${POSTGRES_USER:-orga}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-orga}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: orga_api
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: ["bash", "-lc", "alembic upgrade head && exec uvicorn app.main:app --host ${APP_HOST:-0.0.0.0} --port ${APP_PORT:-8000}"]

volumes:
  db_data:
