services:
  api-dev:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/orga
      APP_ENV: docker
      APP_DEBUG: "false"
      PYTHONPATH: /app/backend:/app
      ALEMBIC_CONFIG: /app/backend/alembic.ini
    working_dir: /app/backend
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 60
    command: ["/bin/bash","-lc","./docker/entrypoint.sh"]
    ports:
      - "8000:8000"
    profiles: ["dev"]

