name: backend

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: orga
        options: >-
          --health-cmd="pg_isready -U postgres -d orga" \
          --health-interval=10s \
          --health-timeout=5s \
          --health-retries=10
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5432/orga
      APP_ENV: ci
      APP_DEBUG: 'false'
      PYTHONPATH: backend:.
      ALEMBIC_CONFIG: backend/alembic.ini
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install fastapi==0.112.2 uvicorn[standard]==0.30.6 SQLAlchemy==2.0.35 \
                     pydantic==2.8.2 pydantic-settings==2.4.0 psycopg[binary]==3.2.1 \
                     alembic==1.13.2 python-multipart==0.0.9 pytest
      - name: Wait for Postgres
        run: |
          for i in {1..60}; do
            pg_isready -h localhost -U postgres -d orga && break
            echo "waiting for postgres..."
            sleep 2
          done
      - name: Apply migrations
        run: |
          cd backend
          alembic upgrade head
      - name: Run tests
        run: |
          pytest -q backend/tests
