name: checks
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  checks:
    defaults:
      run:
        shell: pwsh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Repo tree
        run: pwsh PS1/repo_tree.ps1 && git diff --exit-code docs/REPO_TREE.md
      - name: Guards
        run: pwsh PS1/guards.ps1
      - name: .env.example sanity (robust)
        run: |
          if (-not (Test-Path '.env.example')) { throw '.env.example missing' }
          $nonComment = Select-String -Path '.env.example' -Pattern '^\s*[^#]'
          if (-not $nonComment) { throw '.env.example empty' }
          if (-not (Select-String -Path '.env.example' -Pattern '^APP_ENV=')) { throw 'APP_ENV= missing in .env.example' }
