name: docker-smoke

on:
  push:
    paths:
      - 'backend/**'
      - 'docker-compose.yml'
      - '.github/workflows/docker-smoke.yml'
  pull_request:
    paths:
      - 'backend/**'
      - 'docker-compose.yml'
      - '.github/workflows/docker-smoke.yml'

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and start
        run: |
          docker compose up -d --build db api
      - name: Wait for api health
        run: |
          API_ID=$(docker compose ps -q api)
          echo "API container=$API_ID"
          for i in {1..120}; do
            state=$(docker inspect --format='{{json .State.Health.Status}}' "$API_ID" 2>/dev/null || echo '"starting"')
            echo "health=$state"
            if [ "$state" = '"healthy"' ]; then exit 0; fi
            sleep 2
          done
          echo 'API container not healthy in time'
          docker compose logs --no-color > ci_docker_logs.txt || true
          exit 1
      - name: Show logs on failure
        if: failure()
        run: |
          tail -n 400 ci_docker_logs.txt || true
